apiVersion: v1
kind: Service
metadata:
  name: {{ include "trust-score.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: trust-score
    release: stable
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
