{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
type: Opaque
stringData:
  postgres-password: {{ .Values.postgres.password | quote }}
  sql-alchemy-conn: {{ .Values.secrets.sqlAlchemyConn | quote }}
  fernet-key: {{ .Values.secrets.fernetKey | quote }}
{{- end }}
